---
application:
  name: "quovery-test"
  project: "Test"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "pgdb"
  version: "12"
- type: "REDIS"
  name: "0"
  version: "6"
routers:
- name: "main-quovery-test"
  routes:
  - application_name: "quovery-test"
    paths:
    - "/*"
