---
application:
  name: "quovery-test"
  project: "Tests"
  organization: "QoveryCommunity"
databases:
  - type: postgresql
    version: "13"
    name: db
routers:
  - name: "main-quovery-test"
    routes:
    - application_name: "quovery-test"
      paths:
      - "/*"
