---
application:
  name: "quovery-test"
  project: "Tests"
  organization: "QoveryCommunity"
databases:
  - type: "POSTGRESQL"
    name: "pgdb"
    version: "12"
  - type: "REDIS"
    name: "redis"
    version: "6"
routers:
  - name: "main-quovery-test"
    routes:
    - application_name: "quovery-test"
      paths:
      - "/*"
